# Generated by Django 2.2.4 on 2020-04-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebaritem',
            name='permission_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='权限代码'),
        ),
    ]
