# Generated by Django 2.2.4 on 2020-04-27 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbt', '0002_sidebaritem_permission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebaritem',
            name='permission_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Permission', verbose_name='权限'),
        ),
    ]
