# Generated by Django 2.2.4 on 2020-04-28 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbt', '0003_auto_20200427_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sidebaritem',
            old_name='permission_code',
            new_name='permission',
        ),
    ]
